/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function normalSortNumbers(arr: Float64Array, asc: boolean): void
export function rayonSortNumbers(arr: Float64Array, asc: boolean): void
